branch-defaults:
  master:
    environment: master-RWS
global:
  application_name: RWS
  branch: null
  default_ec2_keyname: rws-key
  default_platform: 64bit Amazon Linux/2.11.0 running Multi-container Docker
  default_region: us-east-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
