branch-defaults:
  master:
    environment: Rws-env1
global:
  application_name: RWS
  branch: null
  default_ec2_keyname: rws-key
  default_platform: 64bit Amazon Linux/2.7.1 running on PHP 7.1
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
